Repository khasang/businessassistant, pull requests merged in 2019-05, with the labels that each got.

#84 Feature/ba-0028 POI entity modify structure (back)
  integrationtest/src/test/java/io/khasang/ba/controller/AddressControllerIntegrationTest.java
  integrationtest/src/test/java/io/khasang/ba/controller/CategoryControllerIntegrationTest.java
  rest/src/main/java/io/khasang/ba/config/AppConfig.java
  rest/src/main/java/io/khasang/ba/controller/AddressController.java
  rest/src/main/java/io/khasang/ba/controller/CategoryController.java
  rest/src/main/java/io/khasang/ba/dao/AddressDao.java
  rest/src/main/java/io/khasang/ba/dao/CategoryDao.java
  rest/src/main/java/io/khasang/ba/dao/impl/AddressDaoImpl.java
  rest/src/main/java/io/khasang/ba/dao/impl/CategoryDaoImpl.java
  rest/src/main/java/io/khasang/ba/entity/Address.java
  rest/src/main/java/io/khasang/ba/entity/Category.java
  rest/src/main/java/io/khasang/ba/service/AddressService.java
  rest/src/main/java/io/khasang/ba/service/CategoryService.java
  rest/src/main/java/io/khasang/ba/service/impl/AddressServiceImpl.java
  rest/src/main/java/io/khasang/ba/service/impl/CategoryServiceImpl.java
Labels: back, feature, testing

#90 Bugfix/ba-0081 Change annotations from NotEmpty to NotBlank for Customer
  integrationtest/src/test/java/io/khasang/ba/controller/CustomerControllerIntegrationTest.java
  rest/src/main/java/io/khasang/ba/entity/Customer.java
Labels: back, bug

#93 Enhancement/ba-0092 Use Lombok for Customer entity
  integrationtest/src/test/java/io/khasang/ba/controller/CustomerControllerIntegrationTest.java
  pom.xml
  rest/src/main/java/io/khasang/ba/entity/Customer.java
  rest/src/main/java/io/khasang/ba/entity/CustomerInformation.java
Labels: back, enhancement

#94 Feature/ba-0051 CustomerRequestType REST layer added
  integrationtest/src/test/java/io/khasang/ba/controller/CustomerRequestTypeIntegrationTest.java
  rest/src/main/java/io/khasang/ba/config/AppConfig.java
  rest/src/main/java/io/khasang/ba/controller/CustomerRequestTypeController.java
  rest/src/main/java/io/khasang/ba/dao/CustomerRequestTypeDao.java
  rest/src/main/java/io/khasang/ba/dao/impl/CustomerRequestTypeDaoImpl.java
  rest/src/main/java/io/khasang/ba/entity/CustomerRequestCategory.java
  rest/src/main/java/io/khasang/ba/entity/CustomerRequestType.java
  rest/src/main/java/io/khasang/ba/service/CustomerRequestTypeService.java
  rest/src/main/java/io/khasang/ba/service/impl/CustomerRequestTypeServiceImpl.java
Labels: back, feature, testing
